config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :spaceships do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[index show edit update destroy]
  get '/garage', to: 'spaceships#garage'
  resources :destinations, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  DESTINATION = %w[Mars Moon]
  belongs_to :spaceship
  belongs_to :user
  belongs_to :destination
  validates :price, :arrive, :depart, :passenger_quantity, presence: true
  # validates :destination, presence: true, inclusion: { in: DESTINATION }
end

app/models/destination.rb
class Destination < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_one_attached :image_url
  validates :name, presence: true
  validates :flight_time, presence: true


    include PgSearch::Model
  pg_search_scope :search_by_name,
    against: [ :name ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/spaceship.rb
class Spaceship < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :destinations, through: :bookings
  has_one_attached :image_url
  validates :name, :description, :cost, presence: true
  validates :capacity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image_url
  has_many :bookings
  has_many :spaceships
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image_url])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image_url])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @spaceships = Spaceship.where(user: current_user)
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @spaceship = Spaceship.find(params[:spaceship_id])
    @destination = Destination.find(params[:query])
    @booking = Booking.new
    # @booking = Booking.new(booking_params)
    # @booking.destination = @destination
    # @booking.approved = false
    # @booking.spaceship = @spaceship
    # @booking.user_id = current_user.id
    # @booking.create
    # @booking.save!
  end

  def create
    @spaceship = Spaceship.find(params[:spaceship_id])
    @destination = Destination.find_by(name: params[:booking][:destination])
    @booking = Booking.new(booking_params)
    @booking.destination = @destination
    @booking.approved = false
    @booking.spaceship = @spaceship
    @booking.user_id = current_user.id
    if @booking.save!
      redirect_to booking_path(@booking)
    else
      render 'new'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:price, :arrive, :depart, :passenger_quantity, :spaceship_id, :user_id, :destination_id)
  end
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def index
    @destinations = Destination.all
  end

  def show
    @destination = Destination.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home; end
end

app/controllers/spaceships_controller.rb
class SpaceshipsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_spaceship, only: %i[show edit update destroy]

  def index
    @spaceships = Spaceship.all
    if params[:query].present?
      @spaceships = Spaceship.where("capacity >= ?", params[:query][:number_of_travellers])
    else
      @spaceships = Spaceship.all
    end
  end

  def show
    if params.key?(:query) && params[:query][:destination].present?
      @destination = Destination.find(params[:query][:destination])
    else
      @destination = Destination.first
    end
  end

  def garage
    if user_check?
      @spaceships = Spaceship.where(user: current_user)
    else
      redirect_to new_spaceship_path
    end
  end

  def new
    @spaceship = Spaceship.new
  end

  def create
    @spaceship = Spaceship.new(spaceship_params)
    @spaceship.user = current_user
    if @spaceship.save
      redirect_to garage_path
    else
      render 'new'
    end
  end

  def edit
    return unless @spaceship.user != current_user
  end

  def update
    @spaceship.update(spaceship_params)
    redirect_to spaceship_path(@spaceship)
  end

  def destroy
    if @spaceship.user == current_user
      @spaceship.destroy
      redirect_to spaceships_path
    else
      redirect_to spaceship_path(@spaceship)
    end
  end

  private

  def spaceship_params
    params.require(:spaceship).permit(:name, :capacity, :description, :image_url, :cost)
  end

  def set_spaceship
    @spaceship = Spaceship.find(params[:id])
  end

  def user_check?
    # returns true for owner, false for user
    current_user.spaceships.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def show
  #   @user = User.find(params[:id])
  # end

  # def new
  #   @user = User.new
  # end

  # def create
  #   @user = User.new(user_params)
  #   @user.save
  #   redirect_to user_path(@user)
  # end

  # private

  # def user_params
  #   params.require(:user).permit(:name, :image_url)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<% @spaceship = Spaceship.find(params[:spaceship_id])%>
<% @destination = Destination.find(params[:query][:destination])%>
<%= simple_form_for [@spaceship, @booking] do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :price, label: "Price (£)", input_html:{ value:"#{@spaceship.cost * @destination.flight_time}" }, readonly: true %>
    <%= f.input :destination, input_html:{ value:"#{@destination.name}" }, readonly: true %>
    <%= f.input :depart, as: :date, required: true, input_html: { min: Date.today }, html5: true %>
    <%= f.input :arrive, label: "Days flight", input_html: { value: "#{@destination.flight_time}" }, readonly: true %>
    <%= f.input :passenger_quantity, label: "Passengers allowed", input_html: { value: "#{@spaceship.capacity}" }, readonly: true %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-submit"  %>
  </div>
<% end %>

app/views/bookings/index.html.erb
<%= render "devise/shared/navbar" %>

<div class="container">


<h1>Welcome to your bookings <%= current_user.name %>! 🚀</h1>

<% if current_user.spaceships.present? %>
  <h2>Your fleet bookings:</h2>
  <% current_user.spaceships.each do |spaceship| %>
    <% if spaceship.bookings.present? %>
       <% spaceship.bookings.each do |booking| %>
        <%= link_to booking_path(booking) do %>
          <div class="card-product">
            <%= cl_image_tag booking.user.image_url.key, height: 200, width: 200, crop: :fill %>
            <div class="card-text">
              <h3>Booking with <%= booking.user.name %></h3>
              <p>Destination: <%= booking.destination.name %></p>
              <p>Depart: <%= booking.depart%></p>
              <p>Travelling on <%= booking.spaceship.name%></p>
              <p>Base cost: £<%= booking.price %></p>       
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
  <br>
  <br>
<% end %>

<h2>Your upcoming trips:</h2>


    <% current_user.bookings.each do |booking| %>
      <%= link_to booking_path(booking) do %>
        <div class="card-product">
          <%= cl_image_tag booking.spaceship.image_url.key, height: 200, width: 200, crop: :fill %>
          <div class="card-text">
            <p>Spacetravellers: <%= booking.passenger_quantity %></p>
            <p>Destination: <%= booking.destination.name %></p>
            <p>Depart: <%= booking.depart%></p>
            <p>Duration: <%= booking.arrive%> days</p>
            <p>TOTAL: £<%= booking.price %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  <br>

  <%= link_to "Search spaceships", spaceships_path, class: "btn btn-flat" %>
  <%= link_to "View garage", garage_path(current_user), class: "btn btn-flat" %>

</div>

app/views/bookings/new.html.erb
<%= render "devise/shared/navbar" %>

<div class="container">
  <h1>Book your spaceship!</h1>
  <%= render 'form' %>
</div>

app/views/bookings/show.html.erb
<%= render "devise/shared/navbar" %>


<div class="row justify-content-center">
  <div class="centred">
    <h2><%= @booking.user.name %>'s trip to <%= @booking.destination.name %></h2>
    <div class="card-trip">
      <div class="img"><%= cl_image_tag @booking.spaceship.image_url.key %></div>
      <div class="card-trip-infos">
        <div>
          <p>Destination: <%= @booking.destination.name %></P>
          <p>Spacetravellers: <%= @booking.passenger_quantity %></p>
          <p>Journey time: <%= @booking.arrive %> days</p>
          <p>Depart: <%= @booking.depart %></p>
        </div>
        <div>
          <%= link_to "Cancel booking",
                      booking_path(@booking),
                      class: "btn btn-flat",
                      method: :delete,
                      data: { confirm: "Are you sure?" } %>
        </div>
      </div>
      </div>
    </div>
    <br>
  </div>
</div>

app/views/destinations/index.html.erb
<%= render "devise/shared/navbar" %>

<p>index page for mars and the moon >> https://www.openplanetary.org/opm</p>

app/views/destinations/show.html.erb
<%= render "devise/shared/navbar" %>


<p>show page for mars or the moon >> https://www.openplanetary.org/opm</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaFusee</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'devise/shared/flashes' %>
    <div class="min-height">
    <%= yield %>
    </div>
    <br>
    <%= render "devise/shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/1vKTnwLMdqs/1920x1281);">
  <div class="container">
    <h1>La Fusee</h1>
    <p>space really is just <strong>one small step</strong>...</p>
    <% if user_signed_in? %>
      <h3 class="white-text">Welcome <%= current_user[:name] %></h3>
        <%= link_to "My spaceships", garage_path, class: "btn btn-flat" %>
        <%= link_to "My bookings",  bookings_path, class: "btn btn-flat" %>

<%= form_tag spaceships_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a movie"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>




    <% else %>
      <%= link_to 'Login', new_user_session_path, class: 'btn btn-flat' %>
      <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-flat' %>
    <% end %>
  </div>
</div>

<div class="header">
  <h2>Explore the stars</h2>
  <h4>Find a rocket</h4>
</div>

<div><%= render 'devise/shared/search_form' %></div>

app/views/spaceships/_form.html.erb
<%= simple_form_for(@spaceship) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, label: "Name:", placeholder: "Sputnik 697" %>
    <%= f.input :capacity, label: "Capacity:" %>
    <%= f.input :description, label: "Description:", placeholder: "The Sputnik 697 spacecraft was the first artificial satellite successfully placed in orbit around the Earth and was launched from Le Wagon in Hoxton (10 km northeast of the small town of Epsom) in UK." %>
    <%= f.input :cost, label: "Cost:", placeholder: "£" %>
    <%= f.input :image_url,
                  label: "Upload a picture of your rocket",
                  as: :file,
                  required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-submit" %>
  </div>
<% end %>

app/views/spaceships/edit.html.erb
<%= render "devise/shared/navbar" %>

<div class="container">
  <h1>Edit your spaceship!</h1>
  <%= render 'form' %>
</div>

app/views/spaceships/garage.html.erb
<%= render "devise/shared/navbar" %>

<div class="container">
  <h2><%= current_user.name %>'s space fleet</h2>
    <div class="card-list">
      <% current_user.spaceships.each do |spaceship| %>
        <%= link_to spaceship_path(spaceship) do %>
          <div class="card-product">
            <%= cl_image_tag spaceship.image_url.key, height: 200, width: 200, crop: :fill %>
            <div class="card-text">
              <h2><%= spaceship.name %></h2><br>
              <p><%= spaceship.description  %></p><br>
              <p>Cost: £<%= spaceship.cost %> <p><br>
              <p>Capacity: <%=spaceship.capacity %></p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <br>
    <%= link_to "Add a new spaceship", new_spaceship_path, class: "btn btn-submit" %>
</div>

app/views/spaceships/index.html.erb
<%= render "devise/shared/navbar" %>

<br>

<div class="container">
  <div id="center"><h3> Find the trip for you! 🛸</h3></div>

  <%# <div><%= render 'devise/shared/search_form' %></div>

  <div class="card-list">
    <% @spaceships.each do |spaceship| %>
      <%= link_to spaceship_path(spaceship,query: @results.first.name) do %>
        <div class="card-product">
          <% if spaceship.user == current_user %>
            <%= cl_image_tag current_user.image_url.key, class: "avatar icon", id: "navbarDropdown", height: 40, width: 300 %>
          <% end %>
          <%= cl_image_tag spaceship.image_url.key, height: 200, width: 200, crop: :fill %>
          <div class="card-text">
            <h2><%= spaceship.name %></h2><br>
            <p><%= spaceship.description  %></p><br>
            <p>Capacity: <%=spaceship.capacity %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/spaceships/new.html.erb
<%= render "devise/shared/navbar" %>


<div class="container">
  <h1>List your spaceship!</h1>
  <%= render 'form' %>
</div>

app/views/spaceships/show.html.erb
<%= render "devise/shared/navbar" %>

<div class="row justify-content-center">
  <div class="centred">
    <% if params.key?(:query) && params[:query][:destination].present? %>
    <div><%= render 'devise/shared/search_form' %></div>
      <h2>Visit <%= @destination.name %> with <%= @spaceship.name %></h2>
        <div class="card-trip">
          <div class="img"><%= cl_image_tag @destination.image_url.key %></div>
          <div class="card-trip-infos">
            <div>
              <h2>Spaceship: <%= @spaceship.name %></h2>
              <p>Description: <%= @spaceship.description %></p>
            </div>
            <div>
              <div>
                <h2>Destination: <%= @destination.name %></h2>
                <p>Flight duration: <%= @destination.flight_time %>days</p>
              </div>
            </div>
            <div>
              <h2 class="card-trip-pricing">Price: £<%= @spaceship.cost * @destination.flight_time %></h2>
              <p>Up to <%= @spaceship.capacity %> passengers</p>
            </div>
          </div>
        </div>
      <br>
      <br>

      <% if @spaceship.user == current_user %>
        <%= link_to "Edit spaceship", edit_spaceship_path, class: "btn btn-flat" %>
        <%= link_to "Delete #{@spaceship.name}",
                    spaceship_path(@spaceship),
                    method: :delete,
                    class: "btn btn-flat",
                    data: { confirm: "Are you sure?" } %>
      <% else %>
        <%= link_to "Make a booking", new_spaceship_booking_path(@spaceship,query: {destination: params.dig(:query, :destination)}), class: "btn btn-submit" %>
      <% end %>
    <% else %>
      <div class="card-trip">
          <div class="img"><%= cl_image_tag @spaceship.image_url.key %></div>
          <div class="card-trip-infos">
            <h2>Spaceship: <%= @spaceship.name %></h2>
            <p>Description: <%= @spaceship.description %></p>
          </div>
      </div>
      <br>
      <br>

      <% if @spaceship.user == current_user %>
        <%= link_to "Edit spaceship", edit_spaceship_path, class: "btn btn-flat" %>
        <%= link_to "Delete #{@spaceship.name}",
                    spaceship_path(@spaceship),
                    method: :delete,
                    class: "btn btn-flat",
                    data: { confirm: "Are you sure?" } %>
      <% else %>
        <%= link_to "Add your own spaceship", new_spaceship_path, class: "btn btn-submit" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/spaceships/user_spaceship.html.erb
<%= render "devise/shared/navbar" %>
<ul>
  <% @spaceships_filtered.each do |spaceship| %>
    <li><%= link_to spaceship.name, spaceship_path(spaceship) %></li>
  <% end %>
</ul>
<br>
<%= link_to "Add a new spaceship", new_spaceship_path %>